### ISSUE TITLE
Missing Download Button

### ISSUE THREAD

**Issue by AMyscich** [jeff-hykin/iilvd-online#3]
Hey Jeff,
I was attempting to download the data I collected and didn't quite see the download button to do so (as referenced by the PDF manual provided). By any chance, do you have any guidance to download the data moving forward?
Attached is the current UI I see.
Please feel free to let me know if you have any questions, comments, or concerns!

![Untitled](https://user-images.githubusercontent.com/34483197/108105738-9d159a80-7052-11eb-8bb1-e2cca908b376.png)

**Comment by jeff-hykin** [comment]
Hey @AMyscich yeah, sorry about that. Since it has the potential to be used for downloading other people's data, Dr. Jiang requested that I remove it. Since the website is only for uploading data, I don't think he saw downloading data as a legitimate need. If you email him and he changes his mind I'll be able to enable it again. 


Sorry about that, I made the instructions before knowing the website would be used in class.

**Comment by AMyscich** [comment]
Sure thing, I'll keep you posted!
